// Generated by gencpp from file duckiepond/Box.msg
// DO NOT EDIT!


#ifndef DUCKIEPOND_MESSAGE_BOX_H
#define DUCKIEPOND_MESSAGE_BOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckiepond
{
template <class ContainerAllocator>
struct Box_
{
  typedef Box_<ContainerAllocator> Type;

  Box_()
    : x(0)
    , y(0)
    , w(0)
    , h(0)
    , confidence(0.0)
    , id(0)  {
    }
  Box_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , w(0)
    , h(0)
    , confidence(0.0)
    , id(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _w_type;
  _w_type w;

   typedef int32_t _h_type;
  _h_type h;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::duckiepond::Box_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckiepond::Box_<ContainerAllocator> const> ConstPtr;

}; // struct Box_

typedef ::duckiepond::Box_<std::allocator<void> > Box;

typedef boost::shared_ptr< ::duckiepond::Box > BoxPtr;
typedef boost::shared_ptr< ::duckiepond::Box const> BoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckiepond::Box_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckiepond::Box_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckiepond

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'duckiepond': ['/home/arg/asv_ros/catkin_ws/src/duckiepond/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond::Box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond::Box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond::Box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond::Box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond::Box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond::Box_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckiepond::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49a6b261b655b7a5a235174ffa9e8810";
  }

  static const char* value(const ::duckiepond::Box_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49a6b261b655b7a5ULL;
  static const uint64_t static_value2 = 0xa235174ffa9e8810ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckiepond::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckiepond/Box";
  }

  static const char* value(const ::duckiepond::Box_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckiepond::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"int32 w\n"
"int32 h\n"
"float32 confidence\n"
"int32 id\n"
;
  }

  static const char* value(const ::duckiepond::Box_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckiepond::Box_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.confidence);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Box_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckiepond::Box_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckiepond::Box_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<int32_t>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<int32_t>::stream(s, indent + "  ", v.h);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIEPOND_MESSAGE_BOX_H
