// Generated by gencpp from file duckiepond/UsvDrive.msg
// DO NOT EDIT!


#ifndef DUCKIEPOND_MESSAGE_USVDRIVE_H
#define DUCKIEPOND_MESSAGE_USVDRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace duckiepond
{
template <class ContainerAllocator>
struct UsvDrive_
{
  typedef UsvDrive_<ContainerAllocator> Type;

  UsvDrive_()
    : header()
    , left(0.0)
    , right(0.0)  {
    }
  UsvDrive_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::duckiepond::UsvDrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckiepond::UsvDrive_<ContainerAllocator> const> ConstPtr;

}; // struct UsvDrive_

typedef ::duckiepond::UsvDrive_<std::allocator<void> > UsvDrive;

typedef boost::shared_ptr< ::duckiepond::UsvDrive > UsvDrivePtr;
typedef boost::shared_ptr< ::duckiepond::UsvDrive const> UsvDriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckiepond::UsvDrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckiepond::UsvDrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckiepond

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'duckiepond': ['/home/arg/asv_ros/catkin_ws/src/duckiepond/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond::UsvDrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond::UsvDrive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond::UsvDrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond::UsvDrive_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckiepond::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7824dbc6876539e023bc92130e483cb";
  }

  static const char* value(const ::duckiepond::UsvDrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7824dbc6876539eULL;
  static const uint64_t static_value2 = 0x023bc92130e483cbULL;
};

template<class ContainerAllocator>
struct DataType< ::duckiepond::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckiepond/UsvDrive";
  }

  static const char* value(const ::duckiepond::UsvDrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckiepond::UsvDrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Standard USV thrust massage - port and starbard\n"
"\n"
"# Thrust command - typically ranges from {-1.0 - 1.0}\n"
"Header header\n"
"float32 left\n"
"float32 right\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckiepond::UsvDrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckiepond::UsvDrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UsvDrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckiepond::UsvDrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckiepond::UsvDrive_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIEPOND_MESSAGE_USVDRIVE_H
