// Generated by gencpp from file duckiepond/VelocityVector.msg
// DO NOT EDIT!


#ifndef DUCKIEPOND_MESSAGE_VELOCITYVECTOR_H
#define DUCKIEPOND_MESSAGE_VELOCITYVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckiepond
{
template <class ContainerAllocator>
struct VelocityVector_
{
  typedef VelocityVector_<ContainerAllocator> Type;

  VelocityVector_()
    : x(0.0)
    , y(0.0)
    , angular(0.0)  {
    }
  VelocityVector_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::duckiepond::VelocityVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckiepond::VelocityVector_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityVector_

typedef ::duckiepond::VelocityVector_<std::allocator<void> > VelocityVector;

typedef boost::shared_ptr< ::duckiepond::VelocityVector > VelocityVectorPtr;
typedef boost::shared_ptr< ::duckiepond::VelocityVector const> VelocityVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckiepond::VelocityVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckiepond::VelocityVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckiepond

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'duckiepond': ['/home/arg/asv_ros/catkin_ws/src/duckiepond/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond::VelocityVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckiepond::VelocityVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond::VelocityVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckiepond::VelocityVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond::VelocityVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckiepond::VelocityVector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckiepond::VelocityVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b6108f70c66951a6da12942857785cf";
  }

  static const char* value(const ::duckiepond::VelocityVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b6108f70c66951aULL;
  static const uint64_t static_value2 = 0x6da12942857785cfULL;
};

template<class ContainerAllocator>
struct DataType< ::duckiepond::VelocityVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckiepond/VelocityVector";
  }

  static const char* value(const ::duckiepond::VelocityVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckiepond::VelocityVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#velocity command {1,-1}\n"
"float32 x\n"
"float32 y\n"
"float32 angular\n"
;
  }

  static const char* value(const ::duckiepond::VelocityVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckiepond::VelocityVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckiepond::VelocityVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckiepond::VelocityVector_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIEPOND_MESSAGE_VELOCITYVECTOR_H
