// Generated by gencpp from file asv_msgs/Heading.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_HEADING_H
#define ASV_MSGS_MESSAGE_HEADING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asv_msgs
{
template <class ContainerAllocator>
struct Heading_
{
  typedef Heading_<ContainerAllocator> Type;

  Heading_()
    : phi(0.0)
    , speed(0.0)  {
    }
  Heading_(const ContainerAllocator& _alloc)
    : phi(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _phi_type;
  _phi_type phi;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::asv_msgs::Heading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv_msgs::Heading_<ContainerAllocator> const> ConstPtr;

}; // struct Heading_

typedef ::asv_msgs::Heading_<std::allocator<void> > Heading;

typedef boost::shared_ptr< ::asv_msgs::Heading > HeadingPtr;
typedef boost::shared_ptr< ::asv_msgs::Heading const> HeadingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv_msgs::Heading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv_msgs::Heading_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'asv_msgs': ['/home/arg/asv_ros/catkin_ws/src/asv_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::Heading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::Heading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::Heading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::Heading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::Heading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::Heading_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv_msgs::Heading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fe8a91eef3de9ae7860b3f07a1529db";
  }

  static const char* value(const ::asv_msgs::Heading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fe8a91eef3de9aeULL;
  static const uint64_t static_value2 = 0x7860b3f07a1529dbULL;
};

template<class ContainerAllocator>
struct DataType< ::asv_msgs::Heading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/Heading";
  }

  static const char* value(const ::asv_msgs::Heading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv_msgs::Heading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 phi\n"
"float32 speed\n"
;
  }

  static const char* value(const ::asv_msgs::Heading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv_msgs::Heading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phi);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Heading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv_msgs::Heading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv_msgs::Heading_<ContainerAllocator>& v)
  {
    s << indent << "phi: ";
    Printer<float>::stream(s, indent + "  ", v.phi);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MSGS_MESSAGE_HEADING_H
