// Generated by gencpp from file asv_msgs/RobotGoal.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_ROBOTGOAL_H
#define ASV_MSGS_MESSAGE_ROBOTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace asv_msgs
{
template <class ContainerAllocator>
struct RobotGoal_
{
  typedef RobotGoal_<ContainerAllocator> Type;

  RobotGoal_()
    : goal()
    , robot()  {
    }
  RobotGoal_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , robot(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _robot_type;
  _robot_type robot;





  typedef boost::shared_ptr< ::asv_msgs::RobotGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv_msgs::RobotGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RobotGoal_

typedef ::asv_msgs::RobotGoal_<std::allocator<void> > RobotGoal;

typedef boost::shared_ptr< ::asv_msgs::RobotGoal > RobotGoalPtr;
typedef boost::shared_ptr< ::asv_msgs::RobotGoal const> RobotGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv_msgs::RobotGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv_msgs::RobotGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'asv_msgs': ['/home/arg/asv_ros/catkin_ws/src/asv_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::RobotGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::RobotGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::RobotGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::RobotGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::RobotGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::RobotGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv_msgs::RobotGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98c7ffdb4ffaa1a7d09b7aef3442e3f1";
  }

  static const char* value(const ::asv_msgs::RobotGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98c7ffdb4ffaa1a7ULL;
  static const uint64_t static_value2 = 0xd09b7aef3442e3f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv_msgs::RobotGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/RobotGoal";
  }

  static const char* value(const ::asv_msgs::RobotGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv_msgs::RobotGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose goal\n"
"geometry_msgs/Pose robot\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::asv_msgs::RobotGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv_msgs::RobotGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.robot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv_msgs::RobotGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv_msgs::RobotGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "robot: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.robot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MSGS_MESSAGE_ROBOTGOAL_H
