// Generated by gencpp from file asv_msgs/SetRobotPathRequest.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_SETROBOTPATHREQUEST_H
#define ASV_MSGS_MESSAGE_SETROBOTPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <asv_msgs/RobotPath.h>

namespace asv_msgs
{
template <class ContainerAllocator>
struct SetRobotPathRequest_
{
  typedef SetRobotPathRequest_<ContainerAllocator> Type;

  SetRobotPathRequest_()
    : data()  {
    }
  SetRobotPathRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::asv_msgs::RobotPath_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotPathRequest_

typedef ::asv_msgs::SetRobotPathRequest_<std::allocator<void> > SetRobotPathRequest;

typedef boost::shared_ptr< ::asv_msgs::SetRobotPathRequest > SetRobotPathRequestPtr;
typedef boost::shared_ptr< ::asv_msgs::SetRobotPathRequest const> SetRobotPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'asv_msgs': ['/home/arg/asv_ros/catkin_ws/src/asv_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "285b52020e3c16265157f0d90cc27df2";
  }

  static const char* value(const ::asv_msgs::SetRobotPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x285b52020e3c1626ULL;
  static const uint64_t static_value2 = 0x5157f0d90cc27df2ULL;
};

template<class ContainerAllocator>
struct DataType< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/SetRobotPathRequest";
  }

  static const char* value(const ::asv_msgs::SetRobotPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asv_msgs/RobotPath data\n"
"\n"
"================================================================================\n"
"MSG: asv_msgs/RobotPath\n"
"geometry_msgs/Pose[] list\n"
"geometry_msgs/Pose robot\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::asv_msgs::SetRobotPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asv_msgs::SetRobotPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asv_msgs::SetRobotPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::asv_msgs::RobotPath_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASV_MSGS_MESSAGE_SETROBOTPATHREQUEST_H
