// Generated by gencpp from file asv_msgs/SetRobotPath.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_SETROBOTPATH_H
#define ASV_MSGS_MESSAGE_SETROBOTPATH_H

#include <ros/service_traits.h>


#include <asv_msgs/SetRobotPathRequest.h>
#include <asv_msgs/SetRobotPathResponse.h>


namespace asv_msgs
{

struct SetRobotPath
{

typedef SetRobotPathRequest Request;
typedef SetRobotPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobotPath
} // namespace asv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asv_msgs::SetRobotPath > {
  static const char* value()
  {
    return "c7fd2b40589889fc45f9427101ed3a2a";
  }

  static const char* value(const ::asv_msgs::SetRobotPath&) { return value(); }
};

template<>
struct DataType< ::asv_msgs::SetRobotPath > {
  static const char* value()
  {
    return "asv_msgs/SetRobotPath";
  }

  static const char* value(const ::asv_msgs::SetRobotPath&) { return value(); }
};


// service_traits::MD5Sum< ::asv_msgs::SetRobotPathRequest> should match 
// service_traits::MD5Sum< ::asv_msgs::SetRobotPath > 
template<>
struct MD5Sum< ::asv_msgs::SetRobotPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asv_msgs::SetRobotPath >::value();
  }
  static const char* value(const ::asv_msgs::SetRobotPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asv_msgs::SetRobotPathRequest> should match 
// service_traits::DataType< ::asv_msgs::SetRobotPath > 
template<>
struct DataType< ::asv_msgs::SetRobotPathRequest>
{
  static const char* value()
  {
    return DataType< ::asv_msgs::SetRobotPath >::value();
  }
  static const char* value(const ::asv_msgs::SetRobotPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asv_msgs::SetRobotPathResponse> should match 
// service_traits::MD5Sum< ::asv_msgs::SetRobotPath > 
template<>
struct MD5Sum< ::asv_msgs::SetRobotPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asv_msgs::SetRobotPath >::value();
  }
  static const char* value(const ::asv_msgs::SetRobotPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asv_msgs::SetRobotPathResponse> should match 
// service_traits::DataType< ::asv_msgs::SetRobotPath > 
template<>
struct DataType< ::asv_msgs::SetRobotPathResponse>
{
  static const char* value()
  {
    return DataType< ::asv_msgs::SetRobotPath >::value();
  }
  static const char* value(const ::asv_msgs::SetRobotPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASV_MSGS_MESSAGE_SETROBOTPATH_H
