// Generated by gencpp from file asv_msgs/SetValue.msg
// DO NOT EDIT!


#ifndef ASV_MSGS_MESSAGE_SETVALUE_H
#define ASV_MSGS_MESSAGE_SETVALUE_H

#include <ros/service_traits.h>


#include <asv_msgs/SetValueRequest.h>
#include <asv_msgs/SetValueResponse.h>


namespace asv_msgs
{

struct SetValue
{

typedef SetValueRequest Request;
typedef SetValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetValue
} // namespace asv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asv_msgs::SetValue > {
  static const char* value()
  {
    return "0aca93dcf6d857f0e5a0dc6be1eaa9fb";
  }

  static const char* value(const ::asv_msgs::SetValue&) { return value(); }
};

template<>
struct DataType< ::asv_msgs::SetValue > {
  static const char* value()
  {
    return "asv_msgs/SetValue";
  }

  static const char* value(const ::asv_msgs::SetValue&) { return value(); }
};


// service_traits::MD5Sum< ::asv_msgs::SetValueRequest> should match 
// service_traits::MD5Sum< ::asv_msgs::SetValue > 
template<>
struct MD5Sum< ::asv_msgs::SetValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asv_msgs::SetValue >::value();
  }
  static const char* value(const ::asv_msgs::SetValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asv_msgs::SetValueRequest> should match 
// service_traits::DataType< ::asv_msgs::SetValue > 
template<>
struct DataType< ::asv_msgs::SetValueRequest>
{
  static const char* value()
  {
    return DataType< ::asv_msgs::SetValue >::value();
  }
  static const char* value(const ::asv_msgs::SetValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asv_msgs::SetValueResponse> should match 
// service_traits::MD5Sum< ::asv_msgs::SetValue > 
template<>
struct MD5Sum< ::asv_msgs::SetValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asv_msgs::SetValue >::value();
  }
  static const char* value(const ::asv_msgs::SetValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asv_msgs::SetValueResponse> should match 
// service_traits::DataType< ::asv_msgs::SetValue > 
template<>
struct DataType< ::asv_msgs::SetValueResponse>
{
  static const char* value()
  {
    return DataType< ::asv_msgs::SetValue >::value();
  }
  static const char* value(const ::asv_msgs::SetValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASV_MSGS_MESSAGE_SETVALUE_H
