(cl:defpackage asv_msgs-srv
  (:use )
  (:export
   "SETROBOTPATH"
   "<SETROBOTPATH-REQUEST>"
   "SETROBOTPATH-REQUEST"
   "<SETROBOTPATH-RESPONSE>"
   "SETROBOTPATH-RESPONSE"
   "SETVALUE"
   "<SETVALUE-REQUEST>"
   "SETVALUE-REQUEST"
   "<SETVALUE-RESPONSE>"
   "SETVALUE-RESPONSE"
  ))

